[build-system]
requires = [
“setuptools>=42”,
“wheel”
]
build-backend = “setuptools.build_meta”




[project]
name = "CollectMiddleware"
version = "0.0.1"
authors = [
  { name="Darix SAMANI", email="samanidarix@gmail.com" },
]
description = "this project consists of creating a middleware to transmit the data collected on an Object Request to a RedisTimeSerie for later analysis"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/darixsamani/CollectMiddleware/"
"Bug Tracker" = "https://github.com/darixsamani/CollectMiddleware/issues"